spring:
  profiles:
    active: dev
  application:
    name: car-ledger-bot
  datasource:
    url: jdbc:mariadb://localhost:3306/car_ledger
    username: root
    password: qwer123$
    driver-class-name: org.mariadb.jdbc.Driver
  liquibase:
    enabled: false
