server:
  port: 8081

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME:KR_CM_bot}
    token: ${TELEGRAM_BOT_TOKEN:8396666705:AAHRLS1Hw7_ecY7z8gyERzqB9EX7VE3ZBD0}

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
