spring:
  threads:
    virtual:
      enabled: true
  profiles:
    active: dev
  application:
    name: car-ledger-web
  datasource:
    url: jdbc:mariadb://localhost:3306/car_ledger?createDatabaseIfNotExist=true
    username: root
    password: qwer123$
    driver-class-name: org.mariadb.jdbc.Driver
  liquibase:
    change-log: classpath:db/changelog-master.xml
    enabled: true

jwt:
  secret: ${JWT_SECRET:c3ByaW5nLWJvb3QtY2FyLWxlZGdlci1zZWNyZXQta2V5LXZhbHVlLTIwMjYtZGVlcG1pbmQtYW50aWdyYXZpdHk=}
  expiration: 3600000 # 1 hour
